import React, { useState } from 'react';
import { Scale, CheckCircle2, XCircle, Copy, Check, Download, ShieldCheck, HeartHandshake, X, ExternalLink, Sparkles } from 'lucide-react';

interface LicenseModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const FULL_LICENSE_TEXT = `POLYFORM NONCOMMERCIAL LICENSE (Version 1.0.0)
NON-PROFIT & EDUCATIONAL RESEARCH USE ONLY

Copyright (c) 2026 engine-harvester Contributors & Open-Source Research Community.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction for Noncommercial and Not-For-Profit purposes,
including without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software for Noncommercial purposes,
subject to the following conditions:

1. NON-PROFIT & NON-COMMERCIAL PURPOSE:
   You may run, modify, study, share, and distribute this Software only for Noncommercial
   and Not-For-Profit purposes. 

   "Noncommercial purposes" means:
   (a) Use by a registered non-profit organization or public charity.
   (b) Academic research, university instruction, and classroom education.
   (c) Personal study, experimentation, evaluation, and non-commercial hobbyist usage.
   (d) Open-source security audits and non-profit public interest research.

2. COMMERCIAL RESTRICTION:
   Commercial use of this Software is strictly prohibited under this license.
   You may NOT:
   (a) Sell, rent, lease, or charge any fee or monetary compensation for the Software
       or any sanitized engine artifact generated by this Software.
   (b) Use the Software to provide commercial paid services, SaaS platforms, or proprietary
       commercial agent offerings.
   (c) Integrate the Software into proprietary commercial closed-source software products
       for commercial exploitation.

3. ATTRIBUTION & NOTICE:
   The above copyright notice and this permission notice shall be included in all
   copies or substantial portions of the Software, as well as generated distribution bundles.

4. NO WARRANTY / AS-IS:
   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
   SOFTWARE.`;

export const LicenseModal: React.FC<LicenseModalProps> = ({ isOpen, onClose }) => {
  const [copied, setCopied] = useState(false);
  const [activeView, setActiveView] = useState<'summary' | 'legal'>('summary');

  if (!isOpen) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(FULL_LICENSE_TEXT);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([FULL_LICENSE_TEXT], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'LICENSE';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div 
        className="bg-slate-900 border border-slate-700/80 rounded-2xl max-w-2xl w-full shadow-2xl overflow-hidden flex flex-col max-h-[90vh] animate-in zoom-in-95 duration-150"
        role="dialog"
        aria-modal="true"
      >
        {/* Modal Header */}
        <div className="px-6 py-4 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-emerald-500 to-teal-700 flex items-center justify-center shadow-md shadow-emerald-950">
              <Scale className="h-5 w-5 text-white" />
            </div>
            <div>
              <div className="flex items-center space-x-2">
                <h3 className="text-base font-bold text-white tracking-tight">Non-Profit &amp; Non-Commercial License</h3>
                <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-emerald-950 text-emerald-300 border border-emerald-700">
                  PolyForm-1.0.0
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Free for non-profit organizations, educational research, and open study
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition-colors cursor-pointer"
            aria-label="Close modal"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* View Switcher Tabs */}
        <div className="flex border-b border-slate-800 bg-slate-950/60 px-6 pt-3 gap-2">
          <button
            onClick={() => setActiveView('summary')}
            className={`pb-2.5 px-3 text-xs font-semibold border-b-2 transition-all cursor-pointer flex items-center space-x-1.5 ${
              activeView === 'summary'
                ? 'border-emerald-400 text-emerald-300'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <HeartHandshake className="h-3.5 w-3.5" />
            <span>Plain English Summary</span>
          </button>
          <button
            onClick={() => setActiveView('legal')}
            className={`pb-2.5 px-3 text-xs font-semibold border-b-2 transition-all cursor-pointer flex items-center space-x-1.5 ${
              activeView === 'legal'
                ? 'border-emerald-400 text-emerald-300'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <ShieldCheck className="h-3.5 w-3.5" />
            <span>Full Legal Text</span>
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto space-y-5 text-xs text-slate-300 leading-relaxed flex-1">
          {activeView === 'summary' ? (
            <div className="space-y-5">
              {/* Grant banner */}
              <div className="p-3.5 rounded-xl bg-emerald-950/40 border border-emerald-800/80 flex items-start space-x-3">
                <HeartHandshake className="h-5 w-5 text-emerald-400 shrink-0 mt-0.5" />
                <div className="flex-1">
                  <h4 className="font-bold text-emerald-200 text-xs">Dedicated to Open Science &amp; Public Benefit</h4>
                  <p className="text-[11px] text-emerald-100/80 mt-0.5">
                    This software and all sanitized architectural specifications are provided free of charge for non-profit entities, academic institutions, and public interest exploration.
                  </p>
                </div>
              </div>

              {/* Preview Link & Free Runnable Quick Access */}
              <div className="p-3.5 rounded-xl bg-slate-950 border border-indigo-900/60 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                <div className="space-y-1">
                  <div className="flex items-center space-x-2">
                    <span className="font-bold text-indigo-300 text-xs">Live Preview Link</span>
                    <span className="inline-flex items-center space-x-1 px-1.5 py-0.5 rounded text-[10px] font-mono bg-emerald-950 text-emerald-300 border border-emerald-800">
                      <Sparkles className="h-2.5 w-2.5" />
                      <span>Free Runnable</span>
                    </span>
                  </div>
                  <div className="text-[11px] font-mono text-slate-400 truncate max-w-md">
                    https://ais-pre-mat3xh2gvcgbmatphxp3nf-483535245139.asia-southeast1.run.app
                  </div>
                </div>
                <a
                  href="https://ais-pre-mat3xh2gvcgbmatphxp3nf-483535245139.asia-southeast1.run.app"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="px-3 py-1.5 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold flex items-center justify-center space-x-1.5 transition-colors shadow-sm cursor-pointer whitespace-nowrap"
                >
                  <ExternalLink className="h-3.5 w-3.5" />
                  <span>Launch Free Web App</span>
                </a>
              </div>

              {/* What is Permitted vs Restricted */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Permitted */}
                <div className="p-4 rounded-xl bg-slate-950 border border-slate-850 space-y-3">
                  <div className="flex items-center space-x-2 text-emerald-400 font-bold text-xs">
                    <CheckCircle2 className="h-4 w-4" />
                    <span>Permitted Non-Profit Uses</span>
                  </div>
                  <ul className="space-y-2 text-[11px] text-slate-300">
                    <li className="flex items-start space-x-2">
                      <span className="text-emerald-400 font-bold">✓</span>
                      <span><strong>Non-Profit Operations</strong>: 501(c)(3) charities and NGOs.</span>
                    </li>
                    <li className="flex items-start space-x-2">
                      <span className="text-emerald-400 font-bold">✓</span>
                      <span><strong>Academic &amp; University</strong>: Classroom instruction and student research.</span>
                    </li>
                    <li className="flex items-start space-x-2">
                      <span className="text-emerald-400 font-bold">✓</span>
                      <span><strong>Open AI Benchmarking</strong>: Comparative agent evaluations and publications.</span>
                    </li>
                    <li className="flex items-start space-x-2">
                      <span className="text-emerald-400 font-bold">✓</span>
                      <span><strong>Personal Learning</strong>: Offline testing and architectural study.</span>
                    </li>
                  </ul>
                </div>

                {/* Prohibited */}
                <div className="p-4 rounded-xl bg-slate-950 border border-slate-850 space-y-3">
                  <div className="flex items-center space-x-2 text-rose-400 font-bold text-xs">
                    <XCircle className="h-4 w-4" />
                    <span>Commercial Prohibitions</span>
                  </div>
                  <ul className="space-y-2 text-[11px] text-slate-300">
                    <li className="flex items-start space-x-2">
                      <span className="text-rose-400 font-bold">✗</span>
                      <span><strong>No Selling or Resale</strong>: Charging money or licensing fees.</span>
                    </li>
                    <li className="flex items-start space-x-2">
                      <span className="text-rose-400 font-bold">✗</span>
                      <span><strong>No Commercial SaaS</strong>: Hosting as a paid commercial service.</span>
                    </li>
                    <li className="flex items-start space-x-2">
                      <span className="text-rose-400 font-bold">✗</span>
                      <span><strong>No Closed-Source Commercial Products</strong>: Embedding in monetized closed platforms.</span>
                    </li>
                    <li className="flex items-start space-x-2">
                      <span className="text-rose-400 font-bold">✗</span>
                      <span><strong>No Paywalled Artifacts</strong>: Restricting access behind commercial paywalls.</span>
                    </li>
                  </ul>
                </div>
              </div>

              {/* Attribution Requirement */}
              <div className="p-3 bg-slate-950 rounded-lg border border-slate-850 text-[11px] text-slate-400 flex items-center justify-between">
                <span>Attribution to <strong>engine-harvester</strong> must be preserved in all derived bundles.</span>
                <span className="text-emerald-400 font-mono font-semibold">CC BY-NC / PolyForm</span>
              </div>
            </div>
          ) : (
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="text-[11px] text-slate-400 font-mono">LICENSE (PolyForm Noncommercial 1.0.0)</span>
                <div className="flex items-center space-x-2">
                  <button
                    onClick={handleCopy}
                    className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-mono flex items-center space-x-1.5 transition-colors cursor-pointer"
                  >
                    {copied ? <Check className="h-3 w-3 text-emerald-400" /> : <Copy className="h-3 w-3" />}
                    <span>{copied ? 'Copied' : 'Copy'}</span>
                  </button>
                  <button
                    onClick={handleDownload}
                    className="px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-mono flex items-center space-x-1.5 transition-colors cursor-pointer"
                  >
                    <Download className="h-3 w-3 text-emerald-400" />
                    <span>Download</span>
                  </button>
                </div>
              </div>
              <pre className="p-4 bg-slate-950 border border-slate-800 rounded-xl font-mono text-[11px] text-slate-300 whitespace-pre-wrap overflow-x-auto leading-relaxed max-h-72">
                {FULL_LICENSE_TEXT}
              </pre>
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="px-6 py-3.5 bg-slate-950 border-t border-slate-800 flex items-center justify-between">
          <div className="text-[11px] text-slate-400 flex items-center space-x-1.5">
            <Scale className="h-3.5 w-3.5 text-emerald-400" />
            <span>Non-Profit &amp; Non-Commercial Research License</span>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handleDownload}
              className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-medium border border-slate-700 transition-colors cursor-pointer flex items-center space-x-1.5"
            >
              <Download className="h-3.5 w-3.5" />
              <span>Download LICENSE</span>
            </button>
            <button
              onClick={onClose}
              className="px-4 py-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold transition-colors cursor-pointer"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
